---
- name: Ensure Docker service is installed & running (cloud-init already did it, but idempotent)
  ansible.builtin.shell: |
    set -e
    command -v docker >/dev/null 2>&1 || sudo dnf -y install docker
    sudo usermod -aG docker ec2-user || true
    sudo systemctl enable --now docker
  args:
    executable: /bin/bash

- name: Ensure docker compose v2 binary exists
  ansible.builtin.shell: |
    set -e
    if ! command -v docker-compose >/dev/null 2>&1; then
      curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
    fi
  args:
    executable: /bin/bash

- name: Create base dir
  ansible.builtin.file:
    path: /opt/gatus
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"
