---
# Install and prepare Docker/Compose only. Do NOT copy gatus files here.

- name: Install Docker if missing (AL2023 uses dnf)
  ansible.builtin.shell: |
    set -e
    if ! command -v docker >/dev/null 2>&1; then
      dnf -y install docker
    fi
  args:
    executable: /bin/bash

- name: Enable and start Docker
  ansible.builtin.shell: |
    systemctl enable --now docker
  args:
    executable: /bin/bash

- name: Ensure docker compose v2 binary exists
  ansible.builtin.shell: |
    set -e
    if ! command -v docker-compose >/dev/null 2>&1; then
      curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
    fi
  args:
    executable: /bin/bash

- name: Create base dir for Gatus
  ansible.builtin.file:
    path: /opt/gatus
    state: directory
    owner: root
    group: root
    mode: "0755"
