name: configure-and-deploy
on:
  push:
    paths:
      - "ansible/**"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION:         ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID:     ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_OIDC_ROLE_NAME: ${{ secrets.AWS_OIDC_ROLE_NAME }}

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
       ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/.ansible/collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Ensure inventory folder
        run: mkdir -p ansible/inventories

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_OIDC_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get EC2 instance id from Terraform outputs
        id: tf
        working-directory: terraform
        run: |
          terraform init -backend-config='bucket=${{ secrets.AWS_TFSTATE_BUCKET }}' \
                         -backend-config='key=terraform/terraform.tfstate' \
                         -backend-config='region=${{ secrets.AWS_REGION }}' \
                         -backend-config='encrypt=true'
          terraform output -raw instance_id > ../ansible/inventories/instance_id

      - name: Setup Python & Ansible
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      
      - name: Install Ansible + AWS collections (explicit path + verify)
        
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws community.general
          ansible-galaxy collection list

      - name: Create inventory using direct connection
        working-directory: ansible
        run: |
          terraform output -raw instance_public_ip > instance_ip.txt
          INSTANCE_IP=$(cat instance_ip.txt)
          cat > inventories/hosts.ini <<EOF
          [aws]
          ${INSTANCE_IP} ansible_connection=local ansible_delegate_to=localhost
          EOF
          echo "Inventory:"
          cat inventories/hosts.ini  
      - name: Run playbook (prepare VM + deploy Gatus)
        working-directory: ansible
        run: |
          ansible --version
          ansible-playbook site.yml -vv
